language: php

php:
- 5.6

cache:
    directories:
        - $HOME/.composer/cache
        - node_modules

before_script:
- nvm install 4.2
- npm install
- cp .env.travis .env
- mysql -e 'create database test_db;'
- composer self-update
- composer install --no-interaction

script:
- vendor/bin/phpunit
- gulp lint
- gulp compile

after_success:
- openssl aes-256-cbc -K $encrypted_625fb94bd2ee_key -iv $encrypted_625fb94bd2ee_iv
  -in secrets.tar.enc -out secrets.tar -d
- tar xvf secrets.tar
- eval "$(ssh-agent -s)"
- chmod 600 ssh_deploy_key
- ssh-add ssh_deploy_key
- cp ssh_config ~/.ssh/config
- cp known_hosts ~/.ssh/known_hosts
- tar -zcvf release.tar.gz app artisan bootstrap database install_release.sh public resources vendor
- scp release.tar.gz otto@remote:/tmp
- ssh otto@remote 'mkdir -p /tmp/release && tar -xvzf /tmp/release.tar.gz -C /tmp/release > /dev/null && bash /tmp/release/install_release.sh'
