language: php

php:
- 5.6

cache:
    directories:
        - $HOME/.composer/cache
        - node_modules

before_script:
- nvm install 4.2
- npm install
- cp .env.travis .env
- mysql -e 'create database test_db;'
- if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
- composer install --no-interaction --prefer-dist

script:
- ./vendor/friendsofphp/php-cs-fixer/php-cs-fixer fix --dry-run . -vv
- mkdir -p build/logs && vendor/bin/phpunit
- gulp lint
- gulp compile

after_success:
- travis_retry php vendor/bin/coveralls -v
- bash deploy.sh # gets rid of dev dependencies, so put last

notifications:
    email: false
