language: php

php:
- 5.6

cache:
    directories:
        - $HOME/.composer/cache
        - node_modules

before_script:
- nvm install 4.2
- npm install
- cp .env.travis .env
- mysql -e 'create database test_db;'
- composer self-update
- composer install --no-interaction --prefer-dist

script:
- vendor/bin/phpunit
- gulp lint
- gulp compile

after_success:
-  bash deploy.sh
