language: php

php:
  - 5.6

before_script:
  - nvm install 4.2
  - npm install
  - cp .env.travis .env
  - mysql -e 'create database test_db;'
  - composer self-update
  - composer install --no-interaction

script:
  - vendor/bin/phpunit
  - gulp lint
  - gulp compile
