language: php

php:
- 7

cache:
    directories:
        - $HOME/.composer/cache
        - node_modules

before_script:
- nvm install 4.2
- npm install
- cp .env.travis .env
- mysql -e 'create database test_db;'
- phpenv config-rm xdebug.ini
- if [ -n "$GH_TOKEN" ]; then composer config github-oauth.github.com ${GH_TOKEN}; fi;
- composer install --no-interaction --prefer-dist

script:
- vendor/bin/phpunit
- gulp lint
- gulp compile

after_success:
-  bash deploy.sh

notifications:
    email: false
